services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: kolping-db

  nuxt:
    build: .
    ports:
      - "3000:3011"
    depends_on:
      - postgres
    volumes:
      - ./kolping-handbuch-data:/data
    environment:
      NUXT_SESSION_PASSWORD: osuadh89453!jhsdf43598??dsf987435879dshufdhhjbdf?sdfbhj
      NUXT_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/kolping-db

volumes:
  postgres-data:
